(source gnu)
(source melpa)
(source melpa-stable)

;; default
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")

(depends-on "nyan-mode")
(depends-on "pallet") ;; package.el と Cask を統合する

(depends-on "yasnippet") ;; 登録したスニペットを呼び出せる
(depends-on "init-loader") ;; 設定ファイル分割できる
(depends-on "auto-complete") ;; 自動補完
(depends-on "undo-tree") ;; Undo / Redo.

(depends-on "clojure-mode") ;; Clojure用プラグイン
(depends-on "cider") ;; ClojureのREPL駆動開発用プラグイン
(depends-on "paredit") ;; カッコの対応関係を整えるプラグイン
(depends-on "monokai-theme") ;; Molokaiのテーマに変える. TODO 本当はMolokaiに統一したいなー

(depends-on "neotree") ;; ツリービュー
(depends-on "helm") ;; 統合インターフェース. TODO もうちょっと時間あるときに設定書く. e.g, https://goo.gl/R1odJj

(depends-on "go-mode") ;; golang用プラグイン

(depends-on "scss-mode") ;; SCSS用プラグイン
